name: CI/CD Pipeline for EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드를 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Java와 빌드 도구 설정
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11' # 사용 중인 JDK 버전에 맞게 설정
          distribution: 'temurin'

      # 3. Maven 또는 Gradle로 빌드
      - name: Build with Maven
        run: |
          cd Kkabi_Backend
          mvn clean package -DskipTests

      # 4. SSH 키 생성
      - name: Set up SSH key
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          echo "$EC2_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
      # 5. jar 파일 압축
      - name: Compress JAR
        run: |
          chmod 500 Kkabi_Backend/target/*.jar
          tar -czf Kkabi_Backend.tar.gz Kkabi_Backend/target/*.jar
          
      # 6. S3에 JAR 업로드
      - name: Upload JAR to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp Kkabi_Backend.tar.gz s3://kkabi-bucket/

      # 6. 압축 파일 EC2로 전송
      - name: Deploy compressed file to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no Kkabi_Backend.tar.gz ${EC2_USER}@${EC2_HOST}:/home/${EC2_USER}/
      
      # 7. jar 파일 실행
      - name: Extract and Run JAR on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << EOF
            aws s3 cp s3://kkabi-bucket/Kkabi_Backend.tar.gz /home/${EC2_USER}/app/
            tar -xzf /home/${EC2_USER}/Kkabi_Backend.tar.gz -C /home/${EC2_USER}/app/
            pkill -f 'java -jar' || true
            nohup java -jar /home/${EC2_USER}/app/*.jar > app.log 2>&1 &
          EOF

